# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: "build and test (go)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        EXCLUDE_DIR: templates
      run: |
        echo "Building all packages..."
        go build -v $(go list ./... | grep -v "$EXCLUDE_DIR")

    - name: Test
      env:
        EXCLUDE_DIR: templates
      run: |
        echo "Running all tests..."
        go test $(go list ./... | grep -v "$EXCLUDE_DIR")

    - name: Lint
      run: |
        echo "Installing golangci-lint..."
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
        echo "Filtering directories with Go files..."
        DIRECTORIES=$(find . -type f -name '*.go' -not -path './templates/*' -exec dirname {} \; | sort -u)
    
        echo "Running golangci-lint on the following directories:"
        echo "$DIRECTORIES"
    
        if [ -n "$DIRECTORIES" ]; then
          golangci-lint run $DIRECTORIES
        else
          echo "No Go files found for linting."
          exit 0
        fi
